CodeSamples/count: Add static to __inline__ function declarations
At lower optimization levels of GCC, __inline__ functions without "static"
cause build errors like below:

    make[1]: Entering directory 'perfbook/CodeSamples/count'
    cc -g -O0 -Wall  -o count_end count_end.c -lpthread
    /usr/bin/ld: /tmp/ccxpkcHA.o: in function `perftestrun':
    perfbook/CodeSamples/count/counttorture.h:159: undefined reference to `count_cleanup'
    /usr/bin/ld: /tmp/ccxpkcHA.o: in function `main':
    perfbook/CodeSamples/count/counttorture.h:248: undefined reference to `count_init'
    collect2: error: ld returned 1 exit status
    make[1]: *** [Makefile:55: count_end] Error 1
    make[1]: Leaving directory 'git/perfbook/CodeSamples/count'

Always put "static" to those function declarations.

While here, add __inline__ to read_count() of count_stack.c.

Signed-off-by: Akira Yokosawa <akiyks@gmail.com>
Signed-off-by: Paul E. McKenney <paulmck@kernel.org>